name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting your first issue! We will get to this ASAP'' first issue'
        pr-message: 'Thanks for submitting your first PR! We will get back to you ASAP'' first pr'
